version: "3"

services:
  nextjs-container:
    image: registry-ebef14e2c4-easynect.apps.ir-thr-ba1.arvancaas.ir/easynect/easynect-frontend:latest
    container_name: user-frontend
    restart: always
    expose:
      - 3000
    networks:
      - easynect_network

    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app-user-frontend.loadbalancer.server.port=3000
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-user-frontend-http.entrypoints=http
      - traefik.http.routers.app-user-frontend-http.rule=Host(`app.easynect.com`)

      # Use the traefik-public network (declared below)
      - traefik.docker.network=easynect
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.app-user-frontend-https.entrypoints=https
      - traefik.http.routers.app-user-frontend-https.rule=Host(`app.easynect.com`)
      - traefik.http.routers.app-user-frontend-https.tls=true

      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.app-user-frontend-https.tls.certresolver=le
      # https-redirect middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.app-user-frontend-http.middlewares=https-redirect

networks:
  easynect_network:
    external:
      name: easynect
